// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bcjhlwmwtbsibprklutq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJjamhsd213dGJzaWJwcmtsdXRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE1MDIwMjQsImV4cCI6MjA3NzA3ODAyNH0.DqJ4mfv6gz8gjI2FfVBZYTnPMSijP8W05RGpqw024cY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});